services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: sbcareerdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
      MYSQL_DB: db-user
    depends_on:
      - sbcareerdb
    networks:
      - twotier

  sbcareerdb:
    build:
      context: ./db
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db-user
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3306:3306"
    networks:
      - twotier
      
networks:
  twotier:
    driver: bridge