apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbcareerapp
  labels:
    app: sbcareerapp
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: sbcareerapp
  template:
    metadata:
      labels:
        app: sbcareerapp
    spec: 
      containers:
        - name: sbcareerapp
          image: sarthakb413/sbcareers-flaskapp
          ports:
            - name: sbcapp-port
              containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: sbcareerdb
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: userdb-pass
            - name: MYSQL_DB
              value: db-user

      initContainers:
        - name: init-sbcareerapp
          image: busybox
          args: ["sh", "-c", "until nslookup sbcareerdb.default.svc.cluster.local; do echo waiting for dbservice; sleep 2; done"]
        
          # initContainers:
          # - name: init-sbcareerapp
          #   image: busybox
          #   command: ["sh", "-c", "echo 'Waiting for dbservice...'; until nslookup sbcareerdb.default.svc.cluster.local; do echo 'Still waiting for dbservice...'; sleep 2; done"]
